version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ekzm
      POSTGRES_PASSWORD: ekzm
      POSTGRES_DB: ekzm
    restart: always
    networks:
      - login-sample
networks:
  login-sample:
